"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/browser";
import { useFinance } from "./use-finance";
type Category = { id:string; name:string; kind:"income"|"expense"; parent_id:string|null; color:string|null };
export function CategoriesPanel() { const { context, error } = useFinance(); const [items,setItems]=useState<Category[]>([]); const [message,setMessage]=useState<string|null>(null); const [open,setOpen]=useState(false);
  const load=async()=>{ if(!context)return; const {data,error}=await createClient().schema("finance").from("categories").select("id,name,kind,parent_id,color").eq("household_id",context.householdId).order("name"); if(error)setMessage("Não foi possível carregar categorias."); else setItems(data as Category[]); };
  useEffect(()=>{void load();},[context?.householdId]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!context)return;const f=new FormData(e.currentTarget);const {error}=await createClient().schema("finance").from("categories").insert({household_id:context.householdId,name:String(f.get("name")),kind:String(f.get("kind")),parent_id:String(f.get("parent_id")||"")||null,color:String(f.get("color")||"")||null});if(error)return setMessage(error.message);setOpen(false);e.currentTarget.reset();void load();}
  async function remove(id:string){if(!confirm("Excluir esta categoria?"))return;const {error}=await createClient().schema("finance").from("categories").delete().eq("id",id);if(error)setMessage("Não é possível excluir uma categoria com lançamentos ou subcategorias.");else void load();}
  if(error)return <section className="empty">{error}</section>; return <section className="ledger"><div className="toolbar"><div><h2>Plano de categorias</h2><p>Organize receitas e despesas em níveis simples.</p></div><button className="button" onClick={()=>setOpen(!open)}>+ Categoria</button></div>{open&&<form className="form-grid" onSubmit={submit}><input required name="name" placeholder="Ex.: Alimentação"/><select name="kind" defaultValue="expense"><option value="expense">Despesa</option><option value="income">Receita</option></select><select name="parent_id" defaultValue=""><option value="">Categoria principal</option>{items.filter(x=>!x.parent_id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="color" placeholder="#16644d (opcional)"/><button className="button">Salvar</button></form>}{message&&<p className="notice">{message}</p>}<div className="tree">{["income","expense"].map(kind=><div key={kind}><h3>{kind==="income"?"Receitas":"Despesas"}</h3>{items.filter(x=>x.kind===kind&&!x.parent_id).map(parent=><div className="tree-parent" key={parent.id}><div><strong>{parent.name}</strong><button onClick={()=>void remove(parent.id)} aria-label="Excluir">×</button></div>{items.filter(x=>x.parent_id===parent.id).map(child=><div className="tree-child" key={child.id}>{child.name}<button onClick={()=>void remove(child.id)} aria-label="Excluir">×</button></div>)}</div>)}</div>)}</div></section>; }
