"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/browser";
import { calculateDashboard, type DashboardTransaction } from "./dashboard";
import { formatBRL } from "./money";
import { useFinance } from "./use-finance";
type Account = { id: string; name: string; opening_balance: string };
type Transaction = DashboardTransaction & { id: string; description: string; categories: { name: string } | null };
type Budget = { amount: string };
export function DashboardPanel() {
  const { context, error } = useFinance(); const [accounts, setAccounts] = useState<Account[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [loadError, setLoadError] = useState<string | null>(null); const now = useMemo(() => new Date(), []); const monthPrefix = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  useEffect(() => { void (async () => { if (!context) return; const db = createClient(); const [accountResult, transactionResult, budgetResult] = await Promise.all([db.schema("finance").from("accounts").select("id,name,opening_balance").eq("household_id", context.householdId).is("archived_at", null), db.schema("finance").from("transactions").select("id,description,kind,status,amount,competency_date,account_id,categories(name)").eq("household_id", context.householdId).order("competency_date", { ascending: false }).limit(250), db.schema("finance").from("budget_items").select("amount").eq("household_id", context.householdId).eq("year", now.getFullYear()).eq("month", now.getMonth() + 1)]); if (accountResult.error || transactionResult.error || budgetResult.error) { setLoadError("Não foi possível atualizar sua visão geral."); return; } setAccounts((accountResult.data ?? []) as Account[]); setTransactions((transactionResult.data ?? []) as unknown as Transaction[]); setBudgets((budgetResult.data ?? []) as Budget[]); })(); }, [context?.householdId, now]);
  if (error) return <section className="empty">{error}</section>; if (loadError) return <section className="empty">{loadError}</section>;
  const budget = budgets.reduce((total, item) => total + Number(item.amount), 0).toFixed(2); const summary = calculateDashboard({ openingBalances: accounts.map((account) => account.opening_balance), transactions, budget, monthPrefix }); const currentMonth = now.toLocaleDateString("pt-BR", { month: "long", year: "numeric" });
  return <section className="dashboard-content"><div className="summary-grid"><article className="card"><span>Saldo em contas</span><strong>{formatBRL(summary.balance)}</strong><small>Somente movimentos liquidados</small></article><article className="card"><span>Receitas em {currentMonth}</span><strong className="income">{formatBRL(summary.income)}</strong><small>Competência do mês</small></article><article className="card"><span>Despesas em {currentMonth}</span><strong className="expense">{formatBRL(summary.expense)}</strong><small>Competência do mês</small></article><article className="card"><span>Orçamento disponível</span><strong className={Number(summary.budgetRemaining) < 0 ? "expense" : "income"}>{formatBRL(summary.budgetRemaining)}</strong><small>de {formatBRL(summary.budget)} planejados</small></article></div><div className="dashboard-split"><section className="recent-list"><div className="toolbar"><div><h2>Movimentos recentes</h2><p>O que foi registrado por último.</p></div><Link className="text-link" href="/lancamentos">Ver livro-caixa</Link></div>{transactions.slice(0, 6).map((transaction) => <div className="recent-row" key={transaction.id}><div><strong>{transaction.description}</strong><span>{transaction.categories?.name ?? "Sem categoria"} · {new Intl.DateTimeFormat("pt-BR").format(new Date(`${transaction.competency_date}T12:00:00`))}</span></div><b className={transaction.kind === "income" ? "income" : "expense"}>{transaction.kind === "income" ? "+ " : "− "}{formatBRL(transaction.amount)}</b></div>)}{!transactions.length && <div className="empty"><strong>Ainda não há movimentos.</strong><p>Crie uma conta e registre sua primeira entrada ou despesa.</p></div>}</section><aside className="next-step"><p className="eyebrow">ATUALIZE SEU LIVRO</p><h2>Um registro por vez.</h2><p>Comece pelo que aconteceu hoje. O painel organiza o resto.</p><Link className="button" href="/lancamentos">+ Novo lançamento</Link><Link className="text-link" href="/contas">Gerenciar contas</Link></aside></div></section>;
}
